### ISSUE TITLE
Device Config Layout Issues

### ISSUE THREAD

**Issue by jopohl** [splotz90/urh#19]
1. Spinboxes are cropped off sometimes. See this screenshot and note the spinboxes on the right;
![image](https://user-images.githubusercontent.com/18219846/27341328-36334f80-55dd-11e7-983c-9dbe15152215.png)
2. Use Spacers to move the widgets closer together.
3. Do not use Tabs but Groupboxes so we can see Send and Receive settings at a glance.

**Comment by splotz90** [comment]
Will be fixed with the next commit ...
