### ISSUE TITLE
Segfault when loading signal

### ISSUE THREAD

**Issue by andynoack** [splotz90/urh#23]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
Loading signals works

## Actual Behavior
$ ./main.py 
Time for generating UI: 0.01 seconds
Adding /tmp/urh/src to pythonpath. This is only important when running URH from source.
linux; GNU C++ version 7.1.1 20170516; Boost_106400; UHD_003.010.001.001-0-unknown

Traceback (most recent call last):
  File "/tmp/urh/src/urh/ui/SimulatorScene.py", line 90, in on_items_added
    self.update_view()
  File "/tmp/urh/src/urh/ui/SimulatorScene.py", line 204, in update_view
    self.arrange_participants()
  File "/tmp/urh/src/urh/ui/SimulatorScene.py", line 258, in arrange_participants
    if any(msg.source == participant or msg.destination == participant for msg in messages):
  File "/tmp/urh/src/urh/ui/SimulatorScene.py", line 258, in <genexpr>
    if any(msg.source == participant or msg.destination == participant for msg in messages):
  File "/tmp/urh/src/urh/signalprocessing/MessageItem.py", line 107, in source
    return self.scene().participants_dict[self.model_item.participant]
KeyError: Participant: Schalter (S)
Abgebrochen (Speicherabzug geschrieben)

## Steps to Reproduce the Problem
  1. Start urh
  2. Load project
  3. Drag loaded signal into simulator

## Platform Specifications
latest manjaro x86_64
  - Python Version:
  - Operating System:
  - Version of URH:

**Comment by splotz90** [comment]
Thank you for reporting this. This issue should be fixed by now.
